import streamlit as st
# -*- coding: utf-8 -*-
"""計程專題_0.3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Es3Zjjx3tgsdTJmII0jFjXjwZo-d14dy
"""

import streamlit as st
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import requests
from io import BytesIO
import time
import os
from typing import List, Optional, Tuple, Dict
from matplotlib.font_manager import FontProperties
import urllib3 
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# ----------------------------------------------------
# 0. STREAMLIT 全域設定與字型處理
# ----------------------------------------------------

st.set_page_config(layout="wide", page_title="廢棄物數據可視化儀表板")

# --- Streamlit 字型載入與設置 ---
font_path = "NotoSansTC-Regular.ttf"
font1: Optional[FontProperties] = None

# 檢查路徑
if os.path.exists(font_path):
    font1 = FontProperties(fname=font_path)
    plt.rcParams['font.sans-serif'] = [font1.get_name()] + plt.rcParams['font.sans-serif']
else:
    plt.rcParams['font.sans-serif'] = ['Arial Unicode MS', 'Microsoft JhengHei', 'SimHei']

plt.rcParams['axes.unicode_minus'] = False

# --- 爬蟲設定 ---
BASE_URL = "https://waste3.moenv.gov.tw/download/waste_web/statistics_file/month/city_output"
HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

# ----------------------------------------------------
# 1. 資料爬取與清理函式 (Cached Function)
# ----------------------------------------------------

@st.cache_data(ttl="1h", show_spinner=False) # 關閉內建 spinner，自己控制進度條
def get_final_data(target_ym_list: List[str]):
    """根據年月代碼抓取、清理並整合資料 (已快取)。"""

    st.info(f"🔗 正在抓取以下年月資料: {target_ym_list}...", icon="⌛")

    all_dataframes: List[pd.DataFrame] = []

    # 使用 Streamlit 的進度條和狀態條
    status_container = st.container()
    progress_bar = status_container.progress(0, text="資料抓取中...")
    latest_status = status_container.empty()

    # --- 批次下載、清理與整合邏輯 ---
    for i, ym_code in enumerate(target_ym_list):
        target_url = f"{BASE_URL}{ym_code}.XLS"
        latest_status.text(f"✅ 正在處理 {ym_code}...")
        progress_bar.progress((i + 1) / len(target_ym_list))

        try:
            response = requests.get(target_url, headers=HEADERS, timeout=15, verify=False)
            time.sleep(0.5)

            if response.status_code == 200:
                data_io = BytesIO(response.content)
                df = pd.read_excel(data_io, sheet_name=0, header=[2, 3])

                # --- 處理多層次標題 ---
                if isinstance(df.columns, pd.MultiIndex):
                    super_header_level = df.columns.get_level_values(0)
                    sub_header_level = df.columns.get_level_values(1)
                    new_columns: List[str] = []

                    for idx, (super_h, sub_h) in enumerate(zip(super_header_level, sub_header_level)):

                        super_h_str = str(super_h).strip()
                        sub_h_str = str(sub_h).strip()

                        if idx == 0: new_columns.append('縣市別')
                        elif idx == 6: new_columns.append('前月貯存量(B)')
                        elif idx == 7: new_columns.append('本月貯存量(C)')
                        elif idx == 8: new_columns.append('貯存異動量(D)=(C)-(B)')
                        elif idx == 9: new_columns.append('廢棄物產生量(E)=(A)+(D)')
                        else:
                            is_single_level = ('Unnamed' in super_h_str or super_h_str.lower() == 'nan' or super_h_str == '')

                            if 'nan' in super_h_str.lower() and idx > 0 and len(new_columns) > 0:
                                super_h_str = new_columns[-1].split(' - ')[0].split('(')[0].strip()

                            if is_single_level and ('Unnamed' in sub_h_str or sub_h_str.lower() == 'nan'): continue

                            if is_single_level:
                                new_columns.append(sub_h_str)
                            elif super_h_str == sub_h_str:
                                new_columns.append(super_h_str)
                            else:
                                new_columns.append(f"{super_h_str} - {sub_h_str}")

                    df.columns = new_columns
                else:
                    df.columns = [str(col).strip() for col in df.columns]

                df['年月代碼'] = ym_code
                all_dataframes.append(df)
                latest_status.success(f"✅ {ym_code} 資料讀取成功！")

            elif response.status_code == 404:
                latest_status.warning(f"⚠️ {ym_code} (404) 資料可能尚未發布。")

        except Exception as e:
            latest_status.error(f"❌ 處理 {ym_code} 錯誤: {e}")
            st.exception(e) # 顯示詳細的錯誤追蹤

    progress_bar.empty()
    latest_status.empty() # 清空最終狀態

    # 彙整所有資料
    if all_dataframes:
        final_df = pd.concat(all_dataframes, ignore_index=True)
        final_df = final_df[~final_df['縣市別'].str.contains('合計|註', na=False)]

        numeric_cols_final = []
        for col in final_df.columns:
            if col not in ['縣市別', '年月代碼']:
                final_df[col] = pd.to_numeric(final_df[col], errors='coerce')
                numeric_cols_final.append(col)

        st.success("🎉 資料抓取與清理完成，開始分析！")
        return final_df, numeric_cols_final
    else:
        st.error("❌ 未能成功抓取任何資料。請檢查年月代碼是否正確。")
        return pd.DataFrame(), []

# ----------------------------------------------------
# 2. 繪圖函式 (Function returns Figure)
# ----------------------------------------------------

def create_single_month_ranking(data: pd.DataFrame, target_month: str, target_col: str):
    """功能 1: 單一月份各縣市排名 (回傳 Figure)"""
    data = data[data['年月代碼'] == target_month].copy()
    if data.empty: return None
    data = data.sort_values(target_col, ascending=False)
    fig, ax = plt.subplots(figsize=(14, 7))
    bars = ax.bar(data['縣市別'], data[target_col], color='skyblue')
    if len(bars) > 3:
        bars[0].set_color('salmon')
        bars[1].set_color('orange')
        bars[2].set_color('gold')
    ax.set_title(f"{target_month} 各縣市 - {target_col} 排名", fontsize=16, fontproperties=font1)
    ax.set_xlabel("縣市別", fontsize=12, fontproperties=font1)
    ax.set_ylabel("數值", fontsize=12, fontproperties=font1)
    ax.tick_params(axis='x', rotation=45)
    for label in ax.get_xticklabels(): label.set_fontproperties(font1)
    ax.grid(axis='y', linestyle='--', alpha=0.7)
    fig.tight_layout()
    return fig

def create_grouped_bar_comparison(data: pd.DataFrame, target_cities: List[str], target_col: str):
    """功能 2: 跨月並排長條圖 (回傳 Figure)"""
    plot_data = data[data['縣市別'].isin(target_cities)]
    if plot_data.empty: return None
    fig, ax = plt.subplots(figsize=(14, 8))
    sns.barplot(
        data=plot_data, x='縣市別', y=target_col, hue='年月代碼', palette='viridis', ax=ax
    )
    ax.set_title(f"{target_col} - 跨月份並排比較", fontsize=16, fontproperties=font1)
    ax.set_ylabel(target_col, fontsize=12, fontproperties=font1)
    ax.set_xlabel("縣市別", fontsize=12, fontproperties=font1)
    ax.tick_params(axis='x', rotation=45)
    for label in ax.get_xticklabels(): label.set_fontproperties(font1)
    ax.legend(title='月份', prop=font1)
    ax.grid(axis='y', linestyle='--', alpha=0.5)
    fig.tight_layout()
    return fig

def create_trend_comparison(data: pd.DataFrame, target_cities: List[str], target_col: str):
    """功能 3: 跨月份趨勢比較 (回傳 Figure)"""
    if len(data['年月代碼'].unique()) < 2: return None
    plot_data = data[data['縣市別'].isin(target_cities)]
    if plot_data.empty: return None
    fig, ax = plt.subplots(figsize=(12, 6))
    sns.lineplot(
        data=plot_data, x='年月代碼', y=target_col, hue='縣市別', marker='o', linewidth=2, ax=ax
    )
    ax.set_title(f"{target_col} - 跨月份趨勢比較", fontsize=16, fontproperties=font1)
    ax.set_xlabel("月份", fontsize=12, fontproperties=font1)
    ax.set_ylabel("數值", fontsize=12, fontproperties=font1)
    ax.legend(prop=font1)
    ax.grid(True, linestyle='--', alpha=0.6)
    fig.tight_layout()
    return fig

# ----------------------------------------------------
# 3. STREAMLIT 應用程式入口 (模擬 CLI 輸入)
# ----------------------------------------------------

def parse_ym_input(input_str: str) -> List[str]:
    """將逗號分隔的年月字串轉換為有效的年月代碼列表"""
    if not input_str:
        return []
    target_ym_list = [
        ym.strip()
        for ym in input_str.split(',')
        if ym.strip().isdigit() and len(ym.strip()) == 5
    ]
    return target_ym_list

def streamlit_app():

    st.title('🗑️ 廢棄物數據可視化儀表板')

    # --- Session State 初始化 ---
    # 用來記住資料是否已經載入成功
    if 'data_loaded' not in st.session_state:
        st.session_state.data_loaded = False
        st.session_state.analysis_df = pd.DataFrame()
        st.session_state.numeric_cols = []
        st.session_state.month_input_str = "" # 記住上次輸入的年月字串

    st.header("1. 選擇資料範圍 ")
    st.info("💡 請輸入想抓取的年月代碼，用逗號分隔 (例如：11405, 11404, 11312)")

    # 模擬 CLI input()
    month_input_string = st.text_input(
        label="年月代碼輸入",
        value=st.session_state.month_input_str, # 記住上次輸入的值
        placeholder="例如: 11405, 11404, 11312",
        key='month_input'
    )

    # 模擬 CLI button/Enter 鍵
    start_button = st.button("開始抓取/更新資料", type='primary')

    # --- 流程控制 ---

    if start_button or st.session_state.data_loaded:

        # 解析輸入並更新 Session State
        target_ym_selection = parse_ym_input(month_input_string)
        st.session_state.month_input_str = month_input_string

        if not target_ym_selection:
            st.error("❌ 輸入格式錯誤或為空。請確認輸入了五位數的年月代碼，並用逗號分隔。")
            st.session_state.data_loaded = False
            return

        # 呼叫快取後的資料載入函式
        analysis_df, numeric_cols = get_final_data(target_ym_selection)

        if analysis_df.empty or not numeric_cols:
            # 錯誤已在 get_final_data 內顯示
            st.session_state.data_loaded = False
            return

        # 資料載入成功，更新 Session State
        st.session_state.data_loaded = True
        st.session_state.analysis_df = analysis_df
        st.session_state.numeric_cols = numeric_cols

    # --- 2. 儀表板分析區 (只有資料載入成功才顯示) ---

    if st.session_state.data_loaded:

        analysis_df = st.session_state.analysis_df
        numeric_cols = st.session_state.numeric_cols

        st.header("2. 數據視覺化儀表板")

        # Streamlit 分割側邊欄和主體，讓選擇更清晰
        col_select, col_chart = st.columns([1, 3])

        with col_select:
            st.subheader("選擇分析條件")

            # 選擇圖表類型
            chart_options = {
                '單月排名 (長條圖)': '1',
                '跨月比較 (並排長條圖)': '2',
                '趨勢分析 (折線圖)': '3'
            }
            chart_name = st.selectbox('圖表類型', list(chart_options.keys()))
            chart_choice = chart_options[chart_name]

            # 選擇分析欄位 (Metric)
            selected_col = st.selectbox('分析指標', numeric_cols)

            # 選擇月份 (僅在單月排名時需要)
            available_months = sorted(analysis_df['年月代碼'].unique(), reverse=True)
            selected_month = None
            if chart_choice == '1':
                selected_month = st.selectbox('分析月份', available_months)

            # 選擇縣市 (Cities)
            all_cities = analysis_df['縣市別'].unique()
            selected_cities = st.multiselect(
                '比較縣市 (多選)',
                all_cities,
                default=list(all_cities)
            )

        with col_chart:
            st.subheader(f"📊 {chart_name}")

            fig = None
            if chart_choice == '1':
                if selected_month:
                    fig = create_single_month_ranking(analysis_df, selected_month, selected_col)
                else:
                    st.info("請選擇月份以顯示單月排名。")

            elif chart_choice == '2':
                if selected_cities:
                    fig = create_grouped_bar_comparison(analysis_df, selected_cities, selected_col)
                else:
                    st.info("請至少選擇一個縣市進行比較。")

            elif chart_choice == '3':
                if len(available_months) < 2:
                    st.error("資料不足，無法繪製趨勢圖 (至少需要兩個月份)")
                elif selected_cities:
                    fig = create_trend_comparison(analysis_df, selected_cities, selected_col)
                else:
                    st.info("請至少選擇一個縣市進行趨勢分析。")

            # 顯示圖表
            if fig:
                st.pyplot(fig)
            elif fig is None:
                pass


if __name__ == '__main__':
    streamlit_app()
